Added: Simulation from a base genome
balabanmetin/tk4-evol-sim pull request #1
Opened 2021-07-03 23:44 UTC by nishatbristy007

2021-07-04 07:08 UTC, balabanmetin requested changes

2021-07-04 07:08 UTC, balabanmetin commented on simulate.py
> +	w = 2*len(idx_occurances[0])/slen
base genome might have characters like "N" and "acgt". The should uppercase everyting. Since N's might exist, slen is not correct. Therefore 
w=(len(idx_occurances[0])+len(idx_occurances[3])/(len(idx_occurances[0])+len(idx_occurances[1])+len(idx_occurances[2])+len(idx_occurances[3]))

2021-07-04 07:08 UTC, balabanmetin commented on simulate.py
> +	pi = np.array([len(i)/slen for i in idx_occurances])
If there is N's the sum of elements in pi will not be 1.

2021-07-04 07:08 UTC, balabanmetin commented on simulate.py
> +	Jc, Hd, F, Pm, R, Flen = params(w,pac,pag,pat,length,pi)
Length is sum of len(idx_occurances[i])

2021-07-04 07:08 UTC, balabanmetin commented on simulate.py
> +			seq1 = rc(seq1)
I think we should randomly flip the first genome no matter what. We don't gain anything by ensuring that simulated genome_0 is identical to input genome, do we?

2021-07-04 15:12 UTC, nishatbristy007 commented on simulate.py
> +	w = 2*len(idx_occurances[0])/slen
Should we remove the N's from the base genomes so that they don't get copied in the simulated genome?

2021-07-05 02:29 UTC, balabanmetin commented on simulate.py
> +	w = 2*len(idx_occurances[0])/slen
Why don't we add a true false parameter `keepunknownchar` to the config file? If false we remove everything besides ATGC (after upper casing). This way we can test if we will know if unknown characters matter

2021-07-05 02:43 UTC, balabanmetin requested changes

2021-07-05 02:43 UTC, balabanmetin commented on simulate.py
> +	w = 2*pi[0]
Isn't w equal to pi[0]+p[3]

2021-07-05 04:03 UTC, nishatbristy007 commented on simulate.py
> +	w = 2*len(idx_occurances[0])/slen
This seems a good idea to me. I have added this to the code.

2021-07-06 00:29 UTC, balabanmetin commented on simulate.py
> +	w = 2*pi[0]
Let's fix this and we are good to merge

2021-07-06 21:52 UTC, balabanmetin approved these changes

2021-07-06 21:52 UTC, merged